CREATE DATABASE "D:\\fbdata\\BOOKSDB.fdb"
USER 'SYSDBA' PASSWORD 'masterkey'
DEFAULT CHARACTER SET UTF8;

-- Create table Publisher
CREATE TABLE Publisher (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) CHARACTER SET UTF8 NOT NULL
);

-- Create table Author
CREATE TABLE Author (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) CHARACTER SET UTF8 NOT NULL,
    surname VARCHAR(255) CHARACTER SET UTF8 NOT NULL
);

-- Create table Ownership State
CREATE TABLE OwnershipState (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) CHARACTER SET UTF8 NOT NULL,
    color VARCHAR(7) CHARACTER SET UTF8 NOT NULL
);
-- Create table Reading State
CREATE TABLE ReadingState (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) CHARACTER SET UTF8 NOT NULL,
    color VARCHAR(7) CHARACTER SET UTF8 NOT NULL
);

-- Create table Book
CREATE TABLE Book (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) CHARACTER SET UTF8 NOT NULL,
    acquirement_date DATE,
    total_pages INTEGER,
    current_page INTEGER,
    total_reads INTEGER DEFAULT 0,
    rating INTEGER CHECK (rating BETWEEN 0 AND 10),
    keywords VARCHAR(500) CHARACTER SET UTF8,
    notes BLOB SUB_TYPE TEXT CHARACTER SET UTF8,
    description BLOB SUB_TYPE TEXT CHARACTER SET UTF8,
    author_id INTEGER NOT NULL,
    publisher_id INTEGER NOT NULL,
    reading_state INTEGER REFERENCES ReadingState (id) ON DELETE SET NULL,
    ownership_state INTEGER REFERENCES OwnershipState (id) ON DELETE SET NULL,
    FOREIGN KEY (author_id) REFERENCES Author (id) ON DELETE CASCADE,
    FOREIGN KEY (publisher_id) REFERENCES Publisher (id) ON DELETE CASCADE
);

-- Insert predefined ownership states
INSERT INTO OwnershipState (name, color) VALUES ('Vlastním', '#00ff00');	-- Green
INSERT INTO OwnershipState (name, color) VALUES ('Nevlastním', '#ff0000');	-- Red
INSERT INTO OwnershipState (name, color) VALUES ('Půjčeno', '#ffff00');		-- Yellow
INSERt INTO OwnershipState (name, color) VALUES ('Prodáno', '#ff5f00');		-- Orange

-- Insert predefined reading states
INSERT INTO ReadingState (name, color) VALUES ('Aktivně čtu', '#00ff00');	-- Green
INSERT INTO ReadingState (name, color) VALUES ('Rozečteno', '#ffff00');		-- Yellow
INSERT INTO ReadingState (name, color) VALUES ('Nechci číst', '#ff0000');	-- Red
INSERT INTO ReadingState (name, color) VALUES ('Chci přečíst', '#ff5f00');	-- Orange

-- Insert predefined publishers
INSERT INTO Publisher (name) VALUES ('Albatros Media');
INSERT INTO Publisher (name) VALUES ('Grada Publishing');
INSERT INTO Publisher (name) VALUES ('Host Brno');

-- Insert predefined authors
INSERT INTO Author (name, surname) VALUES ('Karel', 'Čapek');
INSERT INTO Author (name, surname) VALUES ('Božena', 'Němcová');
INSERT INTO Author (name, surname) VALUES ('Franz', 'Kafka');
INSERT INTO Author (name, surname) VALUES ('Milan', 'Kundera');
INSERT INTO Author (name, surname) VALUES ('Jaroslav', 'Hašek');

-- Insert predefined books
INSERT INTO Book (title, acquirement_date, total_pages, current_page, total_reads, notes, description, keywords, rating, author_id, publisher_id, reading_state, ownership_state)
VALUES ('R.U.R.', '2025-01-01', 96, 0, 0, 'Moc se na tuto knížku těším.', 'Drama o robotech a lidech.', 'sci-fi, roboti, drama', 8, 1, 1, 1, 1);

INSERT INTO Book (title, acquirement_date, total_pages, current_page, total_reads, notes, description, keywords, rating, author_id, publisher_id, reading_state, ownership_state)
VALUES ('Babička', '2025-01-02', 243, 50, 1, 'Nádherná pasáž o přírodě a vztazích.', 'Klasický román české literatury.', 'rodina, příroda, venkov', 9, 2, 2, 2, 2);

INSERT INTO Book (title, acquirement_date, total_pages, current_page, total_reads, notes, description, keywords, rating, author_id, publisher_id, reading_state, ownership_state)
VALUES ('Proměna', '2025-01-03', 72, 15, 2, 'Intenzivní příběh o proměně a izolaci.', 'Příběh o proměně člověka v hmyz.', 'existencialismus, kafka, povídka', 10, 3, 3, 3, 4);

INSERT INTO Book (title, acquirement_date, total_pages, current_page, total_reads, notes, description, keywords, rating, author_id, publisher_id, reading_state, ownership_state)
VALUES ('Žert', '2025-01-10', 240, 0, 0, 'Satirická a podnětná kniha.', 'Román o důsledcích jednoho vtipu.', 'satira, politika, společnost', 8, 4, 1, 1, 1);

INSERT INTO Book (title, acquirement_date, total_pages, current_page, total_reads, notes, description, keywords, rating, author_id, publisher_id, reading_state, ownership_state)
VALUES ('Osudy dobrého vojáka Švejka', '2025-01-11', 752, 100, 1, 'Vtipné a absurdní situace.', 'Dobrodružství vojáka během první světové války.', 'humor, válka, satira', 9, 5, 2, 2, 2);

INSERT INTO Book (title, acquirement_date, total_pages, current_page, total_reads, notes, description, keywords, rating, author_id, publisher_id, reading_state, ownership_state)
VALUES ('Válka s Mloky', '2025-01-12', 312, 50, 2, 'Velmi poučné o lidské povaze.', 'Román o lidech a inteligentních mlokách.', 'sci-fi, dystopie, Čapek', 9, 1, 3, 3, 3);

INSERT INTO Book (title, acquirement_date, total_pages, current_page, total_reads, notes, description, keywords, rating, author_id, publisher_id, reading_state, ownership_state)
VALUES ('Povídky z jedné kapsy', '2025-01-13', 170, 0, 1, 'Zábavné a poutavé příběhy.', 'Sbírka krátkých detektivních povídek.', 'detektivka, záhada, Čapek', 8, 1, 1, 4, 1);

INSERT INTO Book (title, acquirement_date, total_pages, current_page, total_reads, notes, description, keywords, rating, author_id, publisher_id, reading_state, ownership_state)
VALUES ('Kniha smíchu a zapomnění', '2025-01-14', 267, 20, 0, 'Směs humoru a melancholie.', 'Zkoumání paměti a historie.', 'filozofie, paměť, Kundera', 7, 4, 2, 2, 2);

INSERT INTO Book (title, acquirement_date, total_pages, current_page, total_reads, notes, description, keywords, rating, author_id, publisher_id, reading_state, ownership_state)
VALUES ('Proces', '2025-01-15', 220, 50, 2, 'Děsivé a surrealistické.', 'Román o byrokracii a spravedlnosti.', 'Kafka, surrealismus, právo', 9, 3, 1, 3, 4);

INSERT INTO Book (title, acquirement_date, total_pages, current_page, total_reads, notes, description, keywords, rating, author_id, publisher_id, reading_state, ownership_state)
VALUES ('Na západní frontě klid', '2025-01-16', 300, 0, 0, 'Silný příběh o první světové válce.', 'Hrůzy a přátelství během války.', 'válka, tragédie, lidství', 8, 5, 2, 2, 1);

INSERT INTO Book (title, acquirement_date, total_pages, current_page, total_reads, notes, description, keywords, rating, author_id, publisher_id, reading_state, ownership_state)
VALUES ('Nesnesitelná lehkost bytí', '2025-01-17', 320, 30, 1, 'Hluboký román o lásce a osudu.', 'Zkoumání smyslu života a volby.', 'filozofie, Kundera, láska', 9, 4, 3, 1, 3);