CREATE DATABASE "D:\\fbdata\\BOOKSDB.fdb"
USER 'SYSDBA' PASSWORD 'masterkey'
DEFAULT CHARACTER SET UTF8;

-- Create table Publisher
CREATE TABLE Publisher (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) CHARACTER SET UTF8 NOT NULL
);

-- Create table Author
CREATE TABLE Author (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) CHARACTER SET UTF8 NOT NULL,
    surname VARCHAR(255) CHARACTER SET UTF8 NOT NULL
);

-- Create table Ownership State
CREATE TABLE OwnershipState (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) CHARACTER SET UTF8 NOT NULL,
    color VARCHAR(7) CHARACTER SET UTF8 NOT NULL
);
-- Create table Reading State
CREATE TABLE ReadingState (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) CHARACTER SET UTF8 NOT NULL,
    color VARCHAR(7) CHARACTER SET UTF8 NOT NULL
);

-- Create table Book
CREATE TABLE Book (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) CHARACTER SET UTF8 NOT NULL,
    acquirement_date DATE,
    total_pages INTEGER,
    current_page INTEGER,
    total_reads INTEGER DEFAULT 0,
    rating INTEGER CHECK (rating BETWEEN 0 AND 10),
    keywords VARCHAR(500) CHARACTER SET UTF8,
    notes BLOB SUB_TYPE TEXT CHARACTER SET UTF8,
    description BLOB SUB_TYPE TEXT CHARACTER SET UTF8,
    author_id INTEGER NOT NULL,
    publisher_id INTEGER NOT NULL,
    reading_state INTEGER REFERENCES ReadingState (id) ON DELETE SET NULL,
    ownership_state INTEGER REFERENCES OwnershipState (id) ON DELETE SET NULL,
    FOREIGN KEY (author_id) REFERENCES Author (id) ON DELETE CASCADE,
    FOREIGN KEY (publisher_id) REFERENCES Publisher (id) ON DELETE CASCADE
);

-- Insert predefined ownership states
INSERT INTO OwnershipState (name, color) VALUES ('Vlastním', '#00ff00');	-- Green
INSERT INTO OwnershipState (name, color) VALUES ('Nevlastním', '#ff0000');	-- Red
INSERT INTO OwnershipState (name, color) VALUES ('Půjčeno', '#ffff00');	-- Yellow
INSERt INTO OwnershipState (name, color) VALUES ('Prodáno', '#ff5f00');	-- Orange

-- Insert predefined reading states
INSERT INTO ReadingState (name, color) VALUES ('Aktivně čtu', '#00ff00');	-- Green
INSERT INTO ReadingState (name, color) VALUES ('Rozečteno', '#ffff00');	-- Yellow
INSERT INTO ReadingState (name, color) VALUES ('Nechci číst', '#ff0000');	-- Red
INSERT INTO ReadingState (name, color) VALUES ('Chci přečíst', '#ff5f00');	-- Orange

-- Insert predefined publishers
INSERT INTO Publisher (name) VALUES ('Albatros Media');
INSERT INTO Publisher (name) VALUES ('Grada Publishing');
INSERT INTO Publisher (name) VALUES ('Host Brno');

-- Insert predefined authors
INSERT INTO Author (name, surname) VALUES ('Karel', 'Čapek');
INSERT INTO Author (name, surname) VALUES ('Božena', 'Němcová');
INSERT INTO Author (name, surname) VALUES ('Franz', 'Kafka');

-- Insert predefined books
INSERT INTO Book (title, acquirement_date, total_pages, current_page, total_reads, notes, description, keywords, rating, author_id, publisher_id, reading_state, ownership_state)
VALUES ('R.U.R.', '2025-01-01', 96, 0, 0, 'Moc se na tuto knížku těším.', 'Drama o robotech a lidech.', 'sci-fi, roboti, drama', 8, 1, 1, 1, 1);

INSERT INTO Book (title, acquirement_date, total_pages, current_page, total_reads, notes, description, keywords, rating, author_id, publisher_id, reading_state, ownership_state)
VALUES ('Babička', '2025-01-02', 243, 50, 1, 'Nádherná pasáž o přírodě a vztazích.', 'Klasický román české literatury.', 'rodina, příroda, venkov', 9, 2, 2, 2, 2);

INSERT INTO Book (title, acquirement_date, total_pages, current_page, total_reads, notes, description, keywords, rating, author_id, publisher_id, reading_state, ownership_state)
VALUES ('Proměna', '2025-01-03', 72, 15, 2, 'Intenzivní příběh o proměně a izolaci.', 'Příběh o proměně člověka v hmyz.', 'existencialismus, kafka, povídka', 10, 3, 3, 3, 4);

